[pytest]
testpaths = tests
addopts = -ra --strict-markers --capture=tee-sys
markers =
    login: pruebas de autenticación
    catalog: pruebas de navegación y validación del catálogo
    cart: pruebas de interacción con productos y carrito
